### ISSUE TITLE
Reply To

### ISSUE THREAD

**Issue by IzakJackson** [Schotsl/Mailgun#2]
Love this, really helped with my supabase edge functions.

Is it possible to set the reply to address with this?

**Comment by Schotsl** [comment]
Not at the moment. I've just updated the codebase to enable this feature; I'll be testing it and rolling it out in a new release this weekend. :)

**Comment by IzakJackson** [comment]
Awesome, I'll keep my eye out for the commit 🙂

**Comment by dbrxnds** [comment]
Hype!

**Comment by Schotsl** [comment]
I've gone ahead and added support for the reply-to option. To make this happen, you'll need to set a custom email header, and I've made sure type support is in place. I've even created a small code snippet that takes care of adding this header whenever you include a reply property in your email object. Just follow the example I've provided below to see how the email should look with the reply property.

```ts
// Import the Mailgun class
import Mailgun from "https://raw.githubusercontent.com/Schotsl/Mailgun/main/index.ts";

// Create a instance using your Mailgun API key and domain
const mailgun = new Mailgun({
  key: "YOUR_KEY",
  region: "YOUR_REGION",
  domain: "YOUR_DOMAIN",
});

// Send your message off to Mailgun!
await mailgun.send({
  to: "foo@bar.com",
  from: "bar@foo.com",
  text: "How are you doing my friend?",
  reply: "david@foo.com",
  subject: "Just checking up!",
});
```
Keep in mind that I haven't rolled out an official release just yet. I figured it would be best to confirm that everything works as expected for you before making it public. For now, you can import the updated class from https://raw.githubusercontent.com/Schotsl/Mailgun/main/index.ts. Please let me know if it works!

**Comment by IzakJackson** [comment]
Just tested it, and it works like a charm. Cheers @Schotsl - could you let me know when it's pushed live and I'll update my import.

**Comment by Schotsl** [comment]
I've published a new release, which is now accessible at https://deno.land/x/mailgun@v1.2.1. Thank you for your contributions through testing! :)

**Comment by IzakJackson** [comment]
Thanks for getting it added so fast! I just pushed it into production 🙌
