### ISSUE TITLE
Multiple attachments not working

### ISSUE THREAD

**Issue by KevinLeneschmidt** [Schotsl/Mailgun#3]
I am trying to send multiple attachments (should work with Files Arrays aswell), but it does not work. 
![Bildschirmfoto 2024-01-22 um 09 34 19](https://github.com/Schotsl/Mailgun/assets/138887260/ee6c8005-5930-49e2-80cb-7cd60ac1b682)

Everything works fine with 1 File though.

pdfFiles are something like: [
  File {
  name: "first.pdf",
  size: 165169,
  type: "application/pdf"
},
  File {
  name: "second.pdf",
  size: 165170,
  type: "application/pdf"
}

My Example: 
`  const res = await mailgun.send({
    to: email,
    subject: subject,
    from: config.from,
    reply: config.reply,
    attachment: pdfFiles,
  })
`

My mailgun logs:
`"attachments": [
			{
				"size": 36,
				"filename": ".",
				"content-type": "application/octet-stream"
			}
		]`

**Comment by Schotsl** [comment]
Thanks for opening the issue! I think it's a codebase issue (and I might know what it is) but just too be sure, how large are your files? Since Mailgun seems to enforce a 10MB limit, I wanna make sure that isn't the issue :)

**Comment by KevinLeneschmidt** [comment]
Thanks for answering. :)
The files are really small, that can‘t be it.

i also looked at the Codebase and saw, that you are looking if the value is an Array and then you join it, maybe there is the issue.

**Comment by Schotsl** [comment]
Yeah that's what I figured, I've written a (potential) fix that passes the very basic testing suite! Could you maybe try out the fix, you can import the latest version like this: 

```ts
import Mailgun from "https://raw.githubusercontent.com/Schotsl/Mailgun/main/index.ts";
```

I'll release a new version if it works :)

**Comment by KevinLeneschmidt** [comment]
Very nice, it works! I even tested it with 10 files. Thank you very much!

**Comment by Schotsl** [comment]
I've created a [new release](https://github.com/Schotsl/Mailgun/releases/tag/v1.2.2) with the relevant fix!
