### ISSUE TITLE
401 on every attempt

### ISSUE THREAD

**Issue by rienheuver** [Schotsl/Mailgun#4]
Unfortunately I can't get this to work. I tried with various API keys and domains but none seem to work. Any ideas?

**Comment by Schotsl** [comment]
Do you have the correct region? This problem can occur if your Mailgun is set to the EU zone but your API isn't.

**Comment by rienheuver** [comment]
I'm not sure, because I didn't really know what to set the region to. Is there any documentation that you can point me to perhaps?

**Comment by Schotsl** [comment]
You could try this:

```ts
const mailgun = new Mailgun({
  key: "YOUR_KEY",
  region: "eu", // Either "us" or "eu", "us" being default
  domain: "YOUR_DOMAIN",
});
```

**Comment by rienheuver** [comment]
Yes, that fixed it!  Perhaps you could put your snippet in the readme of the repo instead of the current `YOUR_REGION`? To me that was unclear anyway. I can make a PR if you want

**Comment by Schotsl** [comment]
I've updated the `README.md` :)
